server:
    port: 8080
    address: localhost

management.port: 9001

spring:
    profiles: prod
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: 
        databaseName: SpotGarage
        serverName: localhost
        username: SpotGarage
        password:

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            
            

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:


        