version: '2'
services:
  spotgarage-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      - BUCKET=SpotGarage
    # volumes:
    #     - ~/volumes/jhipster/spotgarage/couchbase/:/opt/couchbase/var
